name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files for debug
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./Backend
        run: npm install

      - name: Run backend tests
        working-directory: ./Backend
        run: npm test

      - name: Install frontend dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build MERN image
        run: docker build -t maulik010101/maulik-day9-monitoring-stack:latest .

      - name: Push Docker image to Docker Hub
        run: docker push maulik010101/maulik-day9-monitoring-stack:latest

      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
